### PR TITLE
using bearer token authorization

### PR DESCRIPTION
**Pull request by bogdan-sava**

### CODE REVIEW

**Review by planetf1 — COMMENTED** [review]
I can't test the contents, but do approve that we need this change for v4
For testing with containers we will need a new UI container image/version to be kicked off - either a prerelease for testing, or a final version if happy enough testing has been done

**Review by lpalashevski — APPROVED** [review]

**Comment by sarbull** [comment]
@bogdan-sava why was this merged if the build failed?

**Comment by bogdan-sava** [comment]
the build was successful

**Comment by bogdan-sava** [comment]
https://github.com/odpi/egeria-js-commons/pull/98/checks

**Comment by bogdan-sava** [comment]
that was fixed

**Pull request merged**
